In [5]:
import pandas as pd

In [18]:
filename = 'exch_quoine_btcusd_snapshot_20170407.csv'
data = pandas.read_csv(filename)

In [19]:
data['order_date_time'] = pd.to_datetime(data['order_date_time'], format='%Y-%m-%dD%H:%M:%S.%f000')
data['trades_date_time'] = pd.to_datetime(data['trades_date_time'], format='%Y-%m-%dD%H:%M:%S.%f000')
data

,id,trade_px,trade_volume,b1,b2,b3,b4,b5,a1,a2,...,bq4,bq5,aq1,aq2,aq3,aq4,aq5,order_date_time,trades_date_time,update_type
0,1,0.00,0.000000,1190.70,1190.00,1189.69,1189.22,1188.92,1192.29,1192.30,...,2.236880,1.03688,0.013836,6.640000,1.036880,1.98000,1.03688,2017-04-07 00:00:38.301868,2000-01-01 00:00:00.000000,1
1,3,0.00,0.000000,1190.70,1190.00,1189.69,1189.22,1188.92,1192.30,1193.32,...,2.236880,1.03688,6.640000,1.036880,1.980000,1.03688,1.03688,2017-04-07 00:00:48.770277,2000-01-01 00:00:00.000000,1
2,4,0.00,0.000000,1190.70,1190.00,1189.69,1189.22,1188.92,1192.30,1193.32,...,2.236880,1.03688,1.800000,1.036880,1.980000,1.03688,1.03688,2017-04-07 00:00:54.575567,2000-01-01 00:00:00.000000,1
3,5,0.00,0.000000,1190.70,1190.00,1189.69,1189.22,1188.92,1192.30,1193.32,...,2.236880,1.03688,6.050000,1.036880,1.980000,1.03688,1.03688,2017-04-07 00:00:57.980256,2000-01-01 00:00:00.000000,1
4,6,0.00,0.000000,1190.70,1190.00,1189.69,1189.22,1188.92,1192.29,1192.30,...,2.236880,1.03688,0.014291,6.050000,1.036880,1.98000,1.03688,2017-04-07 00:01:04.378295,2000-01-01 00:00:00.000000,1
5,7,0.00,0.000000,1190.70,1190.00,1189.69,1189.22,1188.92,1191.30,1192.29,...,2.236880,1.03688,1.000000,0.014291,6.050000,1.03688,1.98000,2017-04-07 00:01:06.897093,2000-01-01 00:00:00.000000,1
6,8,1190.70,2.000000,1190.70,1190.00,1189.69,1189.22,1188.92,1191.30,1192.29,...,2.236880,1.03688,1.000000,0.014291,6.050000,1.03688,1.98000,2017-04-07 00:01:06.897093,2017-04-07 00:01:12.563677,2
7,9,1190.70,2.000000,1190.70,1189.26,1189.22,1188.92,1188.90,1191.30,1192.29,...,1.036880,1.20000,5.720000,0.014291,1.800000,1.03688,1.98000,2017-04-07 00:01:13.606592,2017-04-07 00:01:12.563677,1
8,10,1190.70,2.000000,1189.26,1189.22,1188.92,1188.90,1188.82,1190.70,1191.30,...,1.200000,1.20000,0.010000,6.710000,0.014291,1.80000,1.03688,2017-04-07 00:01:18.845970,2017-04-07 00:01:12.563677,1
9,11,1190.70,2.000000,1189.26,1189.22,1188.92,1188.90,1188.82,1190.70,1191.30,...,1.200000,1.20000,0.010000,6.710000,0.014291,1.80000,1.03688,2017-04-07 00:01:19.839065,2017-04-07 00:01:12.563677,1
10,12,1190.70,2.000000,1189.22,1188.92,1188.90,1188.82,1188.80,1190.70,1191.30,...,1.200000,1.20000,0.010000,1.990000,0.014291,1.80000,1.03688,2017-04-07 00:01:22.526876,2017-04-07 00:01:12.563677,1
11,13,1189.26,0.192672,1189.22,1188.92,1188.90,1188.82,1188.80,1190.70,1191.30,...,1.200000,1.20000,0.010000,1.990000,0.014291,1.80000,1.03688,2017-04-07 00:01:22.526876,2017-04-07 00:01:24.022956,2
12,14,1189.26,0.192672,1189.22,1188.92,1188.90,1188.82,1188.80,1190.70,1191.30,...,1.200000,1.20000,4.590000,1.990000,1.800000,1.03688,1.98000,2017-04-07 00:01:30.430814,2017-04-07 00:01:24.022956,1
13,15,1189.26,0.192672,1189.22,1188.92,1188.80,1188.74,1188.70,1190.70,1191.30,...,1.200000,1.83810,4.580000,1.990000,1.800000,1.03688,1.98000,2017-04-07 00:01:31.998623,2017-04-07 00:01:24.022956,1
14,16,1189.26,0.192672,1189.22,1188.92,1188.80,1188.74,1188.70,1190.69,1190.70,...,1.200000,1.83810,0.014291,4.580000,1.990000,1.80000,1.03688,2017-04-07 00:01:40.094145,2017-04-07 00:01:24.022956,1
15,17,1189.26,0.192672,1189.22,1188.92,1188.70,1188.63,1188.49,1190.69,1190.70,...,1.036880,1.20000,0.014291,4.580000,1.990000,1.80000,1.03688,2017-04-07 00:01:52.328912,2017-04-07 00:01:24.022956,1
16,18,1189.26,0.192672,1189.22,1188.92,1188.70,1188.63,1188.33,1190.69,1190.70,...,1.036880,1.03688,0.014291,4.580000,1.990000,1.80000,1.03688,2017-04-07 00:02:00.441611,2017-04-07 00:01:24.022956,1
17,19,1189.22,0.232000,1189.22,1188.92,1188.70,1188.63,1188.33,1190.69,1190.70,...,1.036880,1.03688,0.014291,4.580000,1.990000,1.80000,1.03688,2017-04-07 00:02:00.441611,2017-04-07 00:02:09.664183,2
18,20,1189.22,0.232000,1189.22,1188.92,1188.70,1188.63,1188.33,1190.69,1190.70,...,1.036880,1.03688,0.014291,4.580000,1.990000,1.80000,1.03688,2017-04-07 00:02:11.718661,2017-04-07 00:02:09.664183,1
19,21,1189.22,0.232000,1189.22,1188.92,1188.70,1188.63,1188.44,1190.69,1190.70,...,1.036880,1.20000,0.014291,4.580000,1.990000,1.80000,1.03688,2017-04-07 00:02:24.578264,2017-04-07 00:02:09.664183,1
20,22,1189.22,0.232000,1189.22,1188.92,1188.70,1188.63,1188.44,1190.70,1191.30,...,1.036880,1.20000,4.580000,1.990000,1.800000,1.03688,1.98000,2017-04-07 00:02:38.970305,2017-04-07 00:02:09.664183,1
21,24,1189.22,0.232000,1189.22,1188.92,1188.70,1188.63,1188.44,1190.69,1190.70,...,1.036880,1.20000,0.014291,4.580000,1.990000,1.80000,1.03688,2017-04-07 00:02:50.063620,2017-04-07 00:02:09.664183,1
22,26,1189.22,0.232000,1188.92,1188.70,1188.63,1188.44,1188.33,1190.69,1190.70,...,1.200000,1.03688,0.014291,4.580000,1.990000,1.80000,1.98000,2017-04-07 00:03:06.255189,2017-04-07 00:02:09.664183,1
23,27,1189.22,0.232000,1188.70,1188.63,1188.44,1188.33,1188.12,1190.69,1190.70,...,1.036880,1.20000,0.014291,4.580000,1.990000,1.03800,1.80000,2017-04-07 00:03:08.307752,2017-04-07 00:02:09.664183,1
24,28,1189.22,0.232000,1188.70,1188.63,1188.44,1188.33,1188.12,1190.69,1191.30,...,1.036880,1.20000,0.014291,1.990000,1.038000,1.80000,1.03800,2017-04-07 00:03:09.753584,2017-04-07 00:02:09.664183,1
25,29,1189.22,0.232000,1188.70,1188.63,1188.44,1188.33,1188.12,1190.69,1191.30,...,1.036880,1.20000,4.124291,1.990000,1.038000,1.80000,1.03800,2017-04-07 00:03:16.190788,2017-04-07 00:02:09.664183,1
26,30,1189.22,0.232000,1188.70,1188.44,1188.12,1187.97,1187.84,1190.69,1191.30,...,1.038000,1.20000,4.124291,1.990000,1.038000,1.80000,1.03800,2017-04-07 00:03:17.312130,2017-04-07 00:02:09.664183,1
27,34,1189.22,0.232000,1189.15,1188.84,1188.70,1187.97,1187.84,1190.69,1191.30,...,1.038000,1.20000,4.124291,1.990000,1.038000,1.80000,1.03800,2017-04-07 00:03:36.115987,2017-04-07 00:02:09.664183,1
28,35,1189.22,0.232000,1189.15,1188.84,1188.70,1187.97,1187.70,1190.69,1191.30,...,1.038000,1.84000,4.124291,1.990000,1.038000,1.80000,1.03800,2017-04-07 00:03:46.085992,2017-04-07 00:02:09.664183,1
29,37,1189.22,0.232000,1189.15,1188.84,1188.70,1188.38,1187.97,1190.69,1191.30,...,1.200000,1.03800,4.110000,1.990000,1.038000,1.80000,1.03800,2017-04-07 00:03:55.901087,2017-04-07 00:02:09.664183,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6590,7031,1192.39,0.132500,1192.34,1192.30,1192.05,1191.73,1191.66,1194.80,1194.92,...,1.200000,1.20000,1.999580,1.049490,3.321000,1.04949,1.04949,2017-04-07 23:52:58.195220,2017-04-07 23:41:58.031924,1
6591,7032,1192.39,0.132500,1192.89,1192.57,1192.36,1192.34,1192.30,1194.80,1194.92,...,0.013567,0.89600,1.999580,1.049490,3.321000,1.04949,1.04949,2017-04-07 23:53:41.912036,2017-04-07 23:41:58.031924,1
6592,7033,1192.39,0.132500,1192.89,1192.57,1192.34,1192.30,1191.66,1194.80,1194.92,...,0.896000,1.20000,1.999580,1.049490,3.321000,1.04949,1.04949,2017-04-07 23:53:52.049214,2017-04-07 23:41:58.031924,1
6593,7034,1192.39,0.132500,1192.89,1192.57,1192.33,1192.30,1192.01,1194.80,1194.92,...,0.896000,1.20000,1.999580,1.049490,3.321000,1.04949,1.04949,2017-04-07 23:54:00.908802,2017-04-07 23:41:58.031924,1
6594,7035,1192.39,0.132500,1192.89,1192.57,1192.33,1192.30,1192.01,1194.80,1194.92,...,0.896000,1.20000,1.999580,1.049490,3.321000,1.04949,1.04949,2017-04-07 23:54:32.576969,2017-04-07 23:41:58.031924,1
6595,7036,1192.39,0.132500,1193.21,1192.90,1192.58,1192.30,1192.27,1194.80,1194.92,...,0.896000,1.20000,1.999580,1.049490,3.321000,1.04949,1.04949,2017-04-07 23:55:05.369566,2017-04-07 23:41:58.031924,1
6596,7037,1192.39,0.132500,1193.22,1193.21,1192.90,1192.58,1192.30,1194.80,1194.92,...,1.200000,0.89600,1.999580,1.049490,3.321000,1.04949,1.04949,2017-04-07 23:55:26.595452,2017-04-07 23:41:58.031924,1
6597,7038,1192.39,0.132500,1193.92,1193.60,1193.22,1192.58,1192.30,1194.80,1194.92,...,1.200000,0.89600,1.999580,1.049490,3.321000,1.04949,1.04949,2017-04-07 23:55:51.565358,2017-04-07 23:41:58.031924,1
6598,7039,1192.39,0.132500,1193.92,1193.60,1193.24,1193.22,1192.93,1194.80,1194.92,...,0.014491,1.20000,1.999580,1.049490,3.321000,1.04949,1.04949,2017-04-07 23:55:53.385717,2017-04-07 23:41:58.031924,1
6599,7040,1192.39,0.132500,1193.92,1193.60,1193.24,1192.93,1192.69,1194.80,1194.92,...,1.200000,1.20000,1.999580,1.049490,3.321000,1.04949,1.04949,2017-04-07 23:56:23.448682,2017-04-07 23:41:58.031924,1
6600,7041,1192.39,0.132500,1193.92,1193.60,1193.24,1192.93,1192.69,1194.80,1194.92,...,1.200000,1.20000,1.999580,1.049490,3.321000,1.04949,1.04949,2017-04-07 23:56:33.400257,2017-04-07 23:41:58.031924,1
6601,7042,1192.39,0.132500,1193.93,1193.92,1193.60,1193.24,1192.93,1194.80,1194.92,...,1.200000,1.20000,1.999580,1.049490,3.321000,1.04949,1.04949,2017-04-07 23:56:37.262177,2017-04-07 23:41:58.031924,1
6602,7043,1192.39,0.132500,1193.93,1193.92,1193.60,1193.24,1192.93,1194.80,1194.92,...,1.200000,1.20000,1.999580,1.049490,3.321000,1.04949,1.04949,2017-04-07 23:56:42.909865,2017-04-07 23:41:58.031924,1
6603,7044,1192.39,0.132500,1193.93,1193.92,1193.60,1193.24,1192.93,1194.80,1194.92,...,1.200000,1.20000,1.999580,1.049490,3.321000,1.04949,1.04949,2017-04-07 23:56:43.242369,2017-04-07 23:41:58.031924,1
6604,7045,1192.39,0.132500,1193.93,1193.92,1193.60,1193.24,1192.93,1194.80,1194.92,...,1.200000,1.20000,1.999580,1.049490,3.321000,1.04949,1.04949,2017-04-07 23:56:49.127276,2017-04-07 23:41:58.031924,1
6605,7046,1192.39,0.132500,1193.93,1193.92,1193.60,1193.24,1192.93,1194.80,1195.00,...,1.200000,1.20000,1.999580,3.321000,1.049490,1.04883,1.04949,2017-04-07 23:56:51.874192,2017-04-07 23:41:58.031924,1
6606,7047,1192.39,0.132500,1193.93,1193.92,1193.60,1193.24,1192.93,1194.80,1195.00,...,1.200000,1.20000,1.999580,3.321000,1.048830,1.04883,1.97100,2017-04-07 23:56:56.829077,2017-04-07 23:41:58.031924,1
6607,7048,1192.39,0.132500,1193.93,1193.92,1193.60,1193.24,1192.93,1194.80,1195.00,...,1.200000,1.20000,1.999580,3.321000,1.048830,1.04883,1.97100,2017-04-07 23:57:12.019551,2017-04-07 23:41:58.031924,1
6608,7049,1192.39,0.132500,1193.92,1193.60,1193.24,1192.93,1192.69,1194.80,1195.00,...,1.200000,1.20000,1.999580,3.321000,1.048830,1.04883,1.97100,2017-04-07 23:57:41.333560,2017-04-07 23:41:58.031924,1
6609,7050,1192.39,0.132500,1193.93,1193.92,1193.60,1193.24,1192.93,1194.80,1195.00,...,1.200000,1.20000,1.999580,3.321000,1.048830,1.04883,1.97100,2017-04-07 23:57:47.698757,2017-04-07 23:41:58.031924,1
6610,7051,1192.39,0.132500,1193.93,1193.24,1192.98,1192.93,1192.69,1194.80,1195.00,...,1.200000,1.20000,1.999580,3.321000,1.048830,1.04883,1.97100,2017-04-07 23:57:51.057205,2017-04-07 23:41:58.031924,1
6611,7052,1192.39,0.132500,1193.93,1192.98,1192.67,1192.34,1192.30,1194.80,1195.00,...,1.200000,0.89600,1.999580,3.321000,1.048830,1.04883,1.97100,2017-04-07 23:58:10.659964,2017-04-07 23:41:58.031924,1
6612,7053,1192.39,0.132500,1193.93,1193.41,1193.10,1192.34,1192.30,1194.80,1195.00,...,1.200000,0.89600,1.999580,3.321000,1.048830,1.04883,1.97100,2017-04-07 23:58:34.731977,2017-04-07 23:41:58.031924,1
6613,7054,1192.39,0.132500,1193.93,1193.41,1193.10,1192.88,1192.56,1194.80,1195.00,...,1.200000,1.20000,1.999580,3.321000,1.048830,1.04883,1.97100,2017-04-07 23:58:44.317212,2017-04-07 23:41:58.031924,1
6614,7055,1192.39,0.132500,1193.41,1193.10,1192.88,1192.56,1192.30,1194.80,1195.00,...,1.200000,0.89600,1.999580,3.321000,1.048830,1.04883,1.97100,2017-04-07 23:58:48.524409,2017-04-07 23:41:58.031924,1
6615,7056,1192.39,0.132500,1194.19,1193.87,1192.88,1192.56,1192.30,1194.80,1195.00,...,1.200000,0.89600,1.999580,3.321000,1.048830,1.04883,1.97100,2017-04-07 23:58:55.484805,2017-04-07 23:41:58.031924,1
6616,7057,1192.39,0.132500,1194.20,1194.19,1193.87,1192.56,1192.30,1194.80,1195.00,...,1.200000,0.89600,1.999580,3.321000,1.048830,1.04883,1.97100,2017-04-07 23:59:05.852275,2017-04-07 23:41:58.031924,1
6617,7058,1192.39,0.132500,1194.20,1194.19,1193.87,1193.74,1193.43,1194.80,1195.00,...,1.200000,1.20000,1.999580,3.321000,1.048830,1.04883,1.97100,2017-04-07 23:59:09.022056,2017-04-07 23:41:58.031924,1
6618,7059,1192.39,0.132500,1194.50,1194.20,1194.19,1193.74,1193.43,1194.80,1195.00,...,1.200000,1.20000,1.999580,3.321000,1.048830,1.04883,1.97100,2017-04-07 23:59:46.018619,2017-04-07 23:41:58.031924,1
6619,7060,1192.39,0.132500,1194.50,1194.20,1194.19,1193.91,1193.60,1194.80,1195.00,...,1.200000,1.20000,1.999580,3.321000,1.048830,1.04883,1.97100,2017-04-07 23:59:55.766241,2017-04-07 23:41:58.031924,1

In [29]:
trades = data.loc[data['update_type'] == 2, ["trade_px", "trade_volume", "b1", "bq1", "a1", "aq1", "trades_date_time"]]
trades['trades_hour'] = trades['trades_date_time'].dt.hour
trades

,trade_px,trade_volume,b1,bq1,a1,aq1,trades_date_time,trades_hour
6,1190.700,2.000000,1190.70,0.99000,1191.30,1.000000,2017-04-07 00:01:12.563677,0
11,1189.260,0.192672,1189.22,1.03688,1190.70,0.010000,2017-04-07 00:01:24.022956,0
17,1189.220,0.232000,1189.22,1.03688,1190.69,0.014291,2017-04-07 00:02:09.664183,0
32,1191.300,1.980000,1189.15,1.20000,1190.69,4.720000,2017-04-07 00:04:11.332871,0
38,1190.890,2.000000,1190.70,1.99000,1190.89,3.160000,2017-04-07 00:04:35.806335,0
45,1190.700,2.000000,1190.70,1.99000,1190.89,3.160000,2017-04-07 00:05:41.836592,0
68,1191.300,0.230000,1190.76,1.03553,1191.30,0.885000,2017-04-07 00:11:38.784439,0
116,1190.420,0.145532,1190.42,0.30500,1191.30,5.095000,2017-04-07 00:24:35.438031,0
140,1189.890,0.079132,1189.89,1.03634,1191.29,4.240000,2017-04-07 00:29:52.497017,0
161,1191.280,9.520000,1190.02,1.20000,1191.28,4.760000,2017-04-07 00:37:17.033237,0
163,1191.300,0.480000,1190.02,1.20000,1191.30,0.645000,2017-04-07 00:37:22.112303,0
169,1191.300,3.710000,1190.82,1.20000,1191.30,4.725000,2017-04-07 00:39:53.744280,0
190,1190.920,2.000000,1190.92,1.20000,1191.29,0.014291,2017-04-07 00:45:05.581313,0
198,1190.920,0.320868,1190.42,0.24500,1191.28,0.014291,2017-04-07 00:47:40.580694,0
199,1190.600,2.320868,1190.42,0.24500,1191.28,0.014291,2017-04-07 00:47:41.641804,0
200,1190.420,1.443132,1190.42,0.24500,1191.28,0.014291,2017-04-07 00:47:49.745024,0
221,1188.890,0.243132,1188.89,0.60000,1189.84,1.039820,2017-04-07 00:51:09.825840,0
230,1188.550,0.323800,1188.55,1.03810,1189.30,1.838000,2017-04-07 00:52:25.315254,0
243,1188.750,0.166932,1188.62,1.20000,1188.83,4.024291,2017-04-07 00:55:09.550289,0
250,1188.620,2.000000,1187.95,1.20000,1188.82,4.010000,2017-04-07 00:56:47.385286,0
257,1187.750,0.822732,1187.70,1.28000,1188.30,0.800000,2017-04-07 00:58:04.629790,0
264,1187.700,2.560000,1187.50,1.20000,1188.02,5.331460,2017-04-07 00:58:25.493868,0
280,1187.200,1.600000,1187.20,3.00000,1188.00,0.014291,2017-04-07 01:02:19.652793,1
300,1187.980,3.971418,1187.76,1.03805,1187.98,2.654291,2017-04-07 01:06:27.932660,1
304,1187.980,2.000000,1187.97,2.07406,1187.98,2.654291,2017-04-07 01:06:49.789931,1
306,1187.980,2.000000,1187.97,2.07406,1187.98,1.654291,2017-04-07 01:06:53.356735,1
338,1188.300,0.020000,1188.29,2.40000,1188.30,0.800000,2017-04-07 01:14:15.373939,1
340,1188.690,6.440000,1188.29,2.40000,1188.30,0.780000,2017-04-07 01:14:25.748753,1
345,1189.300,0.680000,1188.68,4.80000,1189.30,1.498000,2017-04-07 01:14:57.683181,1
347,1189.300,1.004000,1188.70,1.00000,1189.30,4.728000,2017-04-07 01:15:03.544104,1
...,...,...,...,...,...,...,...,...
6321,1193.200,0.200000,1193.20,0.64800,1193.40,0.950840,2017-04-07 22:44:22.659169,22
6323,1193.200,0.200000,1193.20,0.54800,1193.40,0.950840,2017-04-07 22:44:30.472208,22
6325,1193.200,0.200000,1193.20,0.54800,1193.21,2.104860,2017-04-07 22:44:39.143152,22
6327,1193.200,0.200000,1193.20,0.44800,1193.21,1.052430,2017-04-07 22:44:57.468522,22
6329,1193.210,0.027145,1193.20,0.34800,1193.21,1.038858,2017-04-07 22:44:59.821623,22
6334,1193.200,0.200000,1193.20,0.24800,1193.24,1.050990,2017-04-07 22:45:18.451876,22
6338,1193.200,0.200000,1193.20,0.24800,1193.79,1.051510,2017-04-07 22:45:37.663661,22
6340,1193.200,0.200000,1193.20,0.14800,1194.08,1.050990,2017-04-07 22:45:50.413051,22
6343,1193.096,0.200000,1193.20,0.04800,1194.30,1.049280,2017-04-07 22:46:12.828718,22
6345,1194.300,0.236000,1193.00,7.94800,1194.30,1.049280,2017-04-07 22:46:20.682381,22
6351,1192.300,0.200000,1193.00,7.94800,1194.29,0.013580,2017-04-07 22:47:21.465176,22
6352,1192.300,0.200000,1193.00,7.94800,1194.29,0.013580,2017-04-07 22:47:24.410906,22
6356,1192.310,0.200000,1192.31,1.90000,1194.80,2.000000,2017-04-07 22:47:49.920913,22
6391,1192.300,0.236000,1192.30,2.11500,1192.31,2.104920,2017-04-07 22:59:48.136602,22
6397,1191.200,2.000000,1191.20,0.01400,1191.80,2.000000,2017-04-07 23:00:30.262104,23
6403,1191.200,0.354000,1191.20,2.29300,1191.80,2.000000,2017-04-07 23:01:01.633840,23
6408,1191.800,2.000000,1191.20,2.29300,1191.80,2.000000,2017-04-07 23:01:50.707986,23
6420,1191.800,2.000000,1191.20,3.29300,1191.80,1.000000,2017-04-07 23:06:48.397011,23
6422,1192.900,0.236000,1191.20,4.29300,1192.90,1.014000,2017-04-07 23:07:13.808973,23
6425,1192.900,1.600000,1192.30,0.80000,1192.90,0.096000,2017-04-07 23:07:31.398637,23
6435,1194.680,0.044000,1192.30,0.89600,1194.68,1.027280,2017-04-07 23:10:52.156684,23
6499,1194.800,3.972840,1194.30,1.20000,1194.80,0.013580,2017-04-07 23:30:14.387859,23
6525,1194.200,0.328000,1194.20,1.98600,1194.80,0.013580,2017-04-07 23:36:57.128506,23
6528,1194.200,0.200000,1194.20,1.72200,1194.80,0.277580,2017-04-07 23:37:23.132612,23
6532,1194.200,2.000000,1194.20,1.72200,1194.80,0.277580,2017-04-07 23:38:32.919083,23
6537,1193.320,0.556000,1193.32,0.92200,1194.80,1.999580,2017-04-07 23:38:45.981668,23
6542,1193.320,0.008000,1192.69,0.40400,1194.80,1.999580,2017-04-07 23:39:33.844268,23
6543,1192.690,1.592000,1192.69,0.40400,1194.80,1.999580,2017-04-07 23:39:42.020661,23
6555,1192.310,2.000000,1192.30,0.89600,1192.31,0.051750,2017-04-07 23:41:52.744851,23
6557,1192.390,0.132500,1192.30,0.89600,1192.39,0.985500,2017-04-07 23:41:58.031924,23

In [32]:
trades.groupby(['trades_hour'])['trade_volume'].sum()

trades_hour
0      34.770800
1      84.042073
2      41.683523
3     114.283249
4     109.823160
5      81.634100
6      65.390292
7      45.596448
8      95.397350
9      25.282492
10     57.227569
11     26.039023
12     15.519905
13     18.081900
14     16.347904
15     25.273801
16     21.089767
17     17.345883
18      4.427000
19     37.386128
20      8.961480
21     51.189871
22     25.903021
23     19.023340
Name: trade_volume, dtype: float64